title: Synapxe - HealthX Innovation Sandbox
url: https://synapxe.sg
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#5b0df5"
  secondary-color: "#5b0df5"
  media-colors:
    - title: media-color-one
      color: "#ff00ff"
    - title: media-color-two
      color: "#3f7cf5"
    - title: media-color-three
      color: "#bf5af5"
    - title: media-color-four
      color: "#942093"
    - title: media-color-five
      color: "#9b9b9b"
description: Synapxe HealthX Innovation Sandbox | Copyright ©2025 Synapxe Pte
  Ltd. All Rights Reserved. Co Reg No.200814464H
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d1hmg150cbkion.amplifyapp.com
prod: https://master.d1hmg150cbkion.amplifyapp.com
resources_name: publications
shareicon: /images/Icons and Logos/icon_hxis api.png
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
google_analytics_ga4: ""
